<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "contact_form_data"
 *
 * Auto generated by Extension Builder 2016-02-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Contact Form Data',
    'description' => 'extension to manage contact form data e.g. topics',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
